// Translations for the instance workspace, content browser, version picker and updater.
// Sections are flattened at export time so components can keep using stable dotted keys.
function flattenSections(sections) {
  return Object.fromEntries(
    Object.entries(sections).flatMap(([section, messages]) =>
      Object.entries(messages).map(([key, value]) => [`${section}.${key}`, value])
    )
  );
}

const en = {
  common: { openFolder: 'Open folder', clear: 'Clear', previous: 'Previous', next: 'Next' },
  cluster: { overview: 'Overview', logs: 'Logs', screenshots: 'Screenshots', mods: 'Mods', shaders: 'Shaders', textures: 'Textures', noneSelected: 'No instance selected.', kill: 'Stop', downloadingPercent: 'Downloading {percent}%', downloading: 'Downloading…', preparing: 'Preparing…', launch: 'Play', vanillaDescription: 'Minecraft {version}, with separate worlds, saves and settings.', loaderDescription: 'Minecraft {version} with {loader}, separate mods, worlds and settings.', openGameFolder: 'Open game folder' },
  clusterSettings: { display: 'GAME DISPLAY', fullscreen: 'Force fullscreen', fullscreenDesc: 'Start the game directly in fullscreen mode', resolution: 'Window resolution', resolutionDesc: 'Default window dimensions', memory: 'MEMORY ALLOCATION', allocatedRam: 'Allocated RAM', allocatedRamDesc: 'Memory available to Minecraft', javaArgs: 'JAVA & LAUNCH ARGUMENTS', javaPath: 'Custom Java path', javaPathDesc: 'Leave blank to use the recommended bundled Java', autoDetected: 'Default (automatically detected)', jvmArgs: 'JVM arguments', jvmArgsDesc: 'Additional command-line arguments passed to Java', directory: 'Instance folder', directoryDesc: 'Local files for this instance', openDirectory: 'Open folder', saved: 'Changes saved', save: 'Save settings' },
  mods: { search: 'Search installed mods…', add: 'Add mods', loading: 'Loading mods…', empty: 'No mods are installed in this instance.', browse: 'Browse mods', byAuthor: 'by {author}', remove: 'Remove mod' },
  logs: { filter: 'Filter logs…', autoScroll: 'Auto-scroll', copied: 'Copied', copy: 'Copy', uploading: 'Uploading…', linkCopied: 'Link copied', upload: 'Upload to mclo.gs', empty: 'No log entries yet. Start this instance to see console output.', noMatch: 'No logs match your filter.' },
  screenshots: { count: '{count} screenshot(s)', loading: 'Loading screenshots…', empty: 'No screenshots have been taken in this instance.', tip: 'Press F2 in Minecraft to take a screenshot.' },
  packs: { shaders: 'Shader packs', resources: 'Resource packs', loading: 'Loading {type}…', empty: 'No {type} installed.', openFolder: 'Open {folder} folder' },
  day: { mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat', sun: 'Sun' },
  overview: { subtitle: 'Play history and servers for {version} {loader}', totalPlaytime: 'Total playtime', sessions: 'Sessions', average: 'Average session', activeDays: 'Active days', serverJoins: 'Server joins', whenYouPlay: 'When you play', mostActive: 'Most active on {day}', peakTime: 'Peak around 4 PM', day: 'Day', hour: 'Hour', dailyPlaytime: 'Daily playtime', total: 'Total', samplePeriod: '27m · Jul 22 – Jul 30' },
  versions: { snapshotDescription: 'Development builds from Mojang. Useful for testing upcoming changes, but they may be unstable.', lineDescription: 'Minecraft {version} releases from the official version manifest. {count} builds are available.', snapshot: 'Snapshot', snapshots: 'Snapshots', experimental: 'Experimental', release: 'Release', unavailable: 'unavailable', created: 'Instance created', ready: '{name} is ready to play.', loadingManifest: 'Loading the Minecraft version manifest…', cachedManifest: 'Showing the cached manifest. Reconnect to refresh it.', subtitle: 'Choose a release, build and mod loader.', fetching: 'Fetching versions from Mojang', installedCount: '{count} installed', buildCount: '{count} build(s)', version: 'Version', selectVersion: 'Select a version', modLoader: 'Mod loader', loaderSnapshotUnavailable: '{loader} does not publish builds for snapshots such as {version}.', loaderNoBuild: '{loader} has no build for {version}.', loaderMinimum: '{loader} supports Minecraft {version} and newer.', loaderNoBuildYet: '{loader} has no build for {version} yet.', alreadyInstalled: 'Already installed as {name}', createInstance: 'Create instance', openInstance: 'Open instance', createAndOpen: 'Create and open', installedVersion: '{version} is installed', configuredAs: 'Configured as {name}', filesPending: 'game files are not downloaded yet', reasonLoader: 'the mod loader is missing', reasonJar: 'the client jar is missing', reasonMetadata: 'the version metadata is missing', reasonAssets: 'the game assets are incomplete', reasonLibraries: 'the libraries are missing', installAndPlay: 'Install & Play' },
  browse: { mods: 'Mods', modpacks: 'Modpacks', shaderpacks: 'Shader packs', resourcepacks: 'Resource packs', datapacks: 'Data packs', relevance: 'Relevance', downloads: 'Downloads', followers: 'Followers', newest: 'Newest', updated: 'Updated', connectionError: 'Could not reach Modrinth. Check your connection and try again.', modpackInstalled: 'Modpack installed', readyToPlay: '{name} is ready to play.', installFailed: 'Installation failed', couldNotInstall: 'Could not install {name}.', noInstanceSelected: 'No instance selected', createBeforeInstall: 'Create an instance before installing content.', noDownloads: 'This project has no downloadable versions.', noExactMatch: 'No exact match', installingLatest: '{name} has no build for {target}. Installing the latest release instead.', thisInstance: 'this instance', noFile: 'That version has no downloadable file.', installed: 'Installed', addedTo: '{name} was added to {instance}.', couldNotRemove: 'Could not remove content', removeFailed: 'Removing that content failed.', subtitle: 'Content from Modrinth, installed directly into an instance.', installingTo: 'Installing to', noInstances: 'No instances', searchType: 'Search {type}', compatibleOnly: 'Only show content compatible with the selected instance', compatibleWith: 'Compatible with {version}', categories: 'Categories', noCategories: 'No categories for this type.', clearFilters: 'Clear filters', searching: 'Searching…', resultCount: '{count} results', installingModpack: 'Installing modpack…', nothingFound: 'Nothing found. Clear category filters or turn off the compatibility filter.', installPack: 'Install pack', licence: 'Licence', author: 'Author', unknown: 'Unknown', loadingVersions: 'Loading version list…', viewOnModrinth: 'View on Modrinth' },
  update: { title: 'Update center', close: 'Close update center', optimizedPatch: 'Optimized patch', package: 'Update package', reusingFiles: 'Reusing files already on this PC; only changed blocks are downloading.', installed: 'Installed', available: 'Available', differential: 'Differential downloads', verified: 'Verified before installation', fullPackage: '{size} full package', whatsNew: 'What’s new', defaultNotes: 'Performance improvements and launcher updates.', couldNotComplete: 'The update could not be completed.', currentVersion: 'Current version {version}', later: 'Later', download: 'Download update', restartLater: 'Restart later', restartInstall: 'Restart and install', cancelDownload: 'Cancel download', applying: 'Applying update…', checking: 'Checking…', check: 'Check for updates', autoTitle: 'Updates are handled automatically', autoText: 'Noctra Client checks quietly and lets you choose when to install.', desktopTitle: 'Desktop updates', desktopText: 'Update checks are available in packaged builds.', checkingTitle: 'Checking for updates', checkingText: 'Looking for the newest stable release…', upToDate: 'You’re up to date', newestVersion: 'Noctra Client {version} is the newest version.', readyTitle: 'Noctra Client {version} is ready', readyText: 'Review the changes, then update when you are ready.', preparingTitle: 'Preparing download', preparingText: 'Comparing this release with the files already installed…', downloadingPercent: 'Downloading {percent}%', changedOnly: 'Only changed parts are being downloaded.', downloadingText: 'Downloading and verifying the update package.', installReady: 'Update ready to install', verifiedRestart: 'Noctra Client {version} is verified. Restart to apply it.', restarting: 'Restarting Noctra Client', applyingMoment: 'The update will be applied in a moment…', interrupted: 'Update interrupted', interruptedText: 'Nothing was installed. Check your connection and try again.', estimating: 'Estimating time…', secondsRemaining: '{count}s remaining', minutesRemaining: '{count}m remaining' },
  settings: { discordPresence: 'Discord Rich Presence' },
  locker: {
    title: 'Locker',
    subtitle: 'Skins, capes and cosmetics for your account.',
    currentSkin: 'Current skin',
    uploadSkin: 'Upload skin',
    dropTitle: 'Drag & drop file',
    dropHint: 'or browse for a PNG',
    uploadCape: 'Upload a cape PNG',
    uploadTitle: 'Uploading texture',
    uploadNotPng: 'Skins and capes must be PNG files.',
    uploadDone: '{name} was added to your locker.',
    capes: 'Capes',
    noCapes: 'No custom capes yet — upload one to get started.',
    noCapeOption: 'No cape',
    officialCape: 'Minecraft cape',
    cloudNote: 'All cosmetics synced to Noctra Cloud',
    favorites: 'Favorites',
    favoritesHint: 'Star a skin to pin it here.',
    latest: 'Latest',
    latestHint: 'Uploads show up here.',
    model: 'Player model',
    modelClassic: 'Classic',
    modelSlim: 'Slim',
    flip: 'Turn around',
    spin: 'Auto-rotate',
    activeSkinNote: 'Wearing {name} in game and on the wardrobe server.',
    noSkinNote: 'Upload a skin to dress this character.',
    apply: 'Wear this',
    favorite: 'Add to favorites',
    unfavorite: 'Remove from favorites',
    publish: 'Apply to my Minecraft profile',
    published: 'Your Minecraft profile now uses this skin.',
    exported: 'Texture saved.',
    exportFailed: 'Could not save that texture.',
    export: 'Save PNG',
    removed: '{name} was removed from your locker.',
    sync: 'Sync to cloud',
    syncHint: 'Publish the active outfit to the Noctra wardrobe server.',
    synced: 'Active outfit published — CustomSkinLoader instances will use it.',
    syncFailed: 'The wardrobe server could not be reached.',
    officialFailed: 'Minecraft rejected that request.',
    actionFailed: 'That action could not be completed.',
    noAccount: 'No account selected',
    noAccountBody: 'Sign in to Noctra Client to upload skins, manage capes and sync cosmetics.'
  },
  home: {
    guest: 'Player',
    greetingMorning: 'Good morning,',
    greetingAfternoon: 'Good afternoon,',
    greetingEvening: 'Good evening,',
    greetingNight: 'Still up,',
    newInstance: 'New instance',
    browseMods: 'Browse mods',
    statPlaytime: 'Total playtime',
    statSessions: 'Sessions played',
    statInstances: 'Instances',
    newsTitle: 'From Minecraft',
    newsSubtitle: 'Official news and updates',
    mostPlayedTitle: 'Most played',
    mostPlayedHint: 'Your top instances',
    noOverviewYet: 'Play an instance and your activity will show up here.',
    emptyBody: 'Create an instance to install a version and start playing.'
  }
};

const es = {
  common: { openFolder: 'Abrir carpeta', clear: 'Limpiar', previous: 'Anterior', next: 'Siguiente' },
  cluster: { overview: 'Resumen', logs: 'Registros', screenshots: 'Capturas', mods: 'Mods', shaders: 'Shaders', textures: 'Texturas', noneSelected: 'No hay ninguna instancia seleccionada.', kill: 'Detener', downloadingPercent: 'Descargando {percent} %', downloading: 'Descargando…', preparing: 'Preparando…', launch: 'Jugar', vanillaDescription: 'Minecraft {version}, con mundos, partidas y ajustes separados.', loaderDescription: 'Minecraft {version} con {loader}, mods, mundos y ajustes separados.', openGameFolder: 'Abrir carpeta del juego' },
  clusterSettings: { display: 'PANTALLA DEL JUEGO', fullscreen: 'Forzar pantalla completa', fullscreenDesc: 'Iniciar el juego directamente a pantalla completa', resolution: 'Resolución de ventana', resolutionDesc: 'Dimensiones predeterminadas de la ventana', memory: 'ASIGNACIÓN DE MEMORIA', allocatedRam: 'RAM asignada', allocatedRamDesc: 'Memoria disponible para Minecraft', javaArgs: 'JAVA Y ARGUMENTOS DE INICIO', javaPath: 'Ruta de Java personalizada', javaPathDesc: 'Déjala vacía para usar el Java incluido recomendado', autoDetected: 'Predeterminado (detección automática)', jvmArgs: 'Argumentos JVM', jvmArgsDesc: 'Argumentos adicionales enviados a Java', directory: 'Carpeta de la instancia', directoryDesc: 'Archivos locales de esta instancia', openDirectory: 'Abrir carpeta', saved: 'Cambios guardados', save: 'Guardar ajustes' },
  mods: { search: 'Buscar mods instalados…', add: 'Añadir mods', loading: 'Cargando mods…', empty: 'No hay mods instalados en esta instancia.', browse: 'Explorar mods', byAuthor: 'de {author}', remove: 'Quitar mod' },
  logs: { filter: 'Filtrar registros…', autoScroll: 'Desplazamiento automático', copied: 'Copiado', copy: 'Copiar', uploading: 'Subiendo…', linkCopied: 'Enlace copiado', upload: 'Subir a mclo.gs', empty: 'Aún no hay registros. Inicia esta instancia para ver la consola.', noMatch: 'Ningún registro coincide con el filtro.' },
  screenshots: { count: '{count} captura(s)', loading: 'Cargando capturas…', empty: 'Aún no hay capturas en esta instancia.', tip: 'Pulsa F2 en Minecraft para hacer una captura.' },
  packs: { shaders: 'Paquetes de shaders', resources: 'Paquetes de recursos', loading: 'Cargando {type}…', empty: 'No hay {type} instalados.', openFolder: 'Abrir carpeta {folder}' },
  day: { mon: 'Lun', tue: 'Mar', wed: 'Mié', thu: 'Jue', fri: 'Vie', sat: 'Sáb', sun: 'Dom' },
  overview: { subtitle: 'Historial de juego y servidores de {version} {loader}', totalPlaytime: 'Tiempo total', sessions: 'Sesiones', average: 'Media por sesión', activeDays: 'Días activos', serverJoins: 'Entradas a servidores', whenYouPlay: 'Cuándo juegas', mostActive: 'Más activo el {day}', peakTime: 'Pico sobre las 16:00', day: 'Día', hour: 'Hora', dailyPlaytime: 'Tiempo diario', total: 'Total', samplePeriod: '27 min · 22 jul – 30 jul' },
  versions: { snapshotDescription: 'Versiones de desarrollo de Mojang. Sirven para probar novedades, pero pueden ser inestables.', lineDescription: 'Versiones de Minecraft {version} del manifiesto oficial. Hay {count} compilaciones.', snapshot: 'Snapshot', snapshots: 'Snapshots', experimental: 'Experimental', release: 'Versión estable', unavailable: 'no disponible', created: 'Instancia creada', ready: '{name} está listo para jugar.', loadingManifest: 'Cargando el manifiesto de versiones de Minecraft…', cachedManifest: 'Se muestra el manifiesto guardado. Vuelve a conectarte para actualizarlo.', subtitle: 'Elige una versión, una compilación y un cargador.', fetching: 'Obteniendo versiones de Mojang', installedCount: '{count} instaladas', buildCount: '{count} compilación(es)', version: 'Versión', selectVersion: 'Selecciona una versión', modLoader: 'Cargador de mods', loaderSnapshotUnavailable: '{loader} no publica versiones para snapshots como {version}.', loaderNoBuild: '{loader} no tiene una versión para {version}.', loaderMinimum: '{loader} admite Minecraft {version} y posteriores.', loaderNoBuildYet: '{loader} aún no tiene una versión para {version}.', alreadyInstalled: 'Ya está instalada como {name}', createInstance: 'Crear instancia', openInstance: 'Abrir instancia', createAndOpen: 'Crear y abrir' },
  browse: { mods: 'Mods', modpacks: 'Modpacks', shaderpacks: 'Paquetes de shaders', resourcepacks: 'Paquetes de recursos', datapacks: 'Paquetes de datos', relevance: 'Relevancia', downloads: 'Descargas', followers: 'Seguidores', newest: 'Más recientes', updated: 'Actualizados', connectionError: 'No se pudo conectar con Modrinth. Comprueba la conexión e inténtalo de nuevo.', modpackInstalled: 'Modpack instalado', readyToPlay: '{name} está listo para jugar.', installFailed: 'Error de instalación', couldNotInstall: 'No se pudo instalar {name}.', noInstanceSelected: 'No hay instancia seleccionada', createBeforeInstall: 'Crea una instancia antes de instalar contenido.', noDownloads: 'Este proyecto no tiene versiones descargables.', noExactMatch: 'No hay coincidencia exacta', installingLatest: '{name} no tiene una versión para {target}. Se instalará la última versión.', thisInstance: 'esta instancia', noFile: 'Esa versión no tiene un archivo descargable.', installed: 'Instalado', addedTo: '{name} se añadió a {instance}.', couldNotRemove: 'No se pudo quitar el contenido', removeFailed: 'No se pudo quitar ese contenido.', subtitle: 'Contenido de Modrinth instalado directamente en una instancia.', installingTo: 'Instalar en', noInstances: 'Sin instancias', searchType: 'Buscar {type}', compatibleOnly: 'Mostrar solo contenido compatible con la instancia', compatibleWith: 'Compatible con {version}', categories: 'Categorías', noCategories: 'No hay categorías para este tipo.', clearFilters: 'Limpiar filtros', searching: 'Buscando…', resultCount: '{count} resultados', installingModpack: 'Instalando modpack…', nothingFound: 'No se encontró nada. Limpia las categorías o desactiva el filtro de compatibilidad.', installPack: 'Instalar paquete', licence: 'Licencia', author: 'Autor', unknown: 'Desconocido', loadingVersions: 'Cargando versiones…', viewOnModrinth: 'Ver en Modrinth' },
  update: { title: 'Centro de actualizaciones', close: 'Cerrar actualizaciones', optimizedPatch: 'Parche optimizado', package: 'Paquete de actualización', reusingFiles: 'Se reutilizan los archivos del equipo; solo se descargan los bloques modificados.', installed: 'Instalada', available: 'Disponible', differential: 'Descargas diferenciales', verified: 'Verificada antes de instalar', fullPackage: 'Paquete completo de {size}', whatsNew: 'Novedades', defaultNotes: 'Mejoras de rendimiento y del launcher.', couldNotComplete: 'No se pudo completar la actualización.', currentVersion: 'Versión actual: {version}', later: 'Más tarde', download: 'Descargar actualización', restartLater: 'Reiniciar más tarde', restartInstall: 'Reiniciar e instalar', cancelDownload: 'Cancelar descarga', applying: 'Aplicando actualización…', checking: 'Comprobando…', check: 'Buscar actualizaciones', autoTitle: 'Actualizaciones automáticas', autoText: 'Noctra Client busca actualizaciones sin molestar y tú eliges cuándo instalarlas.', desktopTitle: 'Actualizaciones de escritorio', desktopText: 'La búsqueda de actualizaciones está disponible en la aplicación instalada.', checkingTitle: 'Buscando actualizaciones', checkingText: 'Buscando la versión estable más reciente…', upToDate: 'Todo está actualizado', newestVersion: 'Noctra Client {version} es la versión más reciente.', readyTitle: 'Noctra Client {version} está disponible', readyText: 'Revisa los cambios y actualiza cuando quieras.', preparingTitle: 'Preparando la descarga', preparingText: 'Comparando esta versión con los archivos instalados…', downloadingPercent: 'Descargando {percent} %', changedOnly: 'Solo se descargan las partes modificadas.', downloadingText: 'Descargando y verificando la actualización.', installReady: 'Actualización lista para instalar', verifiedRestart: 'Noctra Client {version} está verificado. Reinicia para aplicarlo.', restarting: 'Reiniciando Noctra Client', applyingMoment: 'La actualización se aplicará en un momento…', interrupted: 'Actualización interrumpida', interruptedText: 'No se instaló nada. Comprueba la conexión e inténtalo de nuevo.', estimating: 'Calculando tiempo…', secondsRemaining: 'Quedan {count} s', minutesRemaining: 'Quedan {count} min' },
  storage: { fullyInstalled: '{count} instaladas por completo', tracked: 'registrado por Noctra Client', worlds: 'Mundos', acrossInstances: 'en todas las instancias', packs: 'Paquetes', packsDesc: 'paquetes de recursos y shaders', recorded: 'registrado por el launcher', localCache: 'Caché local', cacheDesc: 'manifiesto, imágenes y ajustes', perInstance: 'Por instancia', scanning: 'Analizando', rescan: 'Volver a analizar', empty: 'Aún no hay instancias; no se usa espacio en disco.', notDownloaded: 'Sin descargar', modCount: '{count} mods', worldCount: '{count} mundos', resourcePacks: 'Paquetes de recursos', shaderPacks: 'Paquetes de shaders', lastPlayed: 'Última partida', never: 'Nunca', instanceFolder: 'Carpeta de instancia', cachedData: 'Datos en caché', clearCaches: 'Vaciar cachés de descarga', cacheEmpty: 'vacía' },
  changelog: { error: 'No se pudo conectar con GitHub. Conéctate a internet para ver las notas.', checking: 'Buscando versiones', upToDate: 'Noctra Client está actualizado', available: 'La versión {version} está disponible', notes: 'Notas de la versión', running: 'Estás usando {version}', localBuild: 'Compilación local', allReleases: 'Todas las versiones', loading: 'Cargando notas…', noReleases: 'Aún no hay versiones publicadas.', installed: 'Instalada', latest: 'Más reciente', noNotes: 'No hay notas para esta versión.', openGitHub: 'Abrir en GitHub' },
  settings: { discordPresence: 'Presencia enriquecida de Discord' }
};

const de = {
  common: { openFolder: 'Ordner öffnen', clear: 'Leeren', previous: 'Zurück', next: 'Weiter' },
  cluster: { overview: 'Übersicht', logs: 'Protokolle', screenshots: 'Screenshots', mods: 'Mods', shaders: 'Shader', textures: 'Texturen', noneSelected: 'Keine Instanz ausgewählt.', kill: 'Stoppen', downloadingPercent: 'Download {percent} %', downloading: 'Wird heruntergeladen…', preparing: 'Wird vorbereitet…', launch: 'Spielen', vanillaDescription: 'Minecraft {version} mit getrennten Welten, Spielständen und Einstellungen.', loaderDescription: 'Minecraft {version} mit {loader} sowie getrennten Mods, Welten und Einstellungen.', openGameFolder: 'Spielordner öffnen' },
  clusterSettings: { display: 'SPIELANZEIGE', fullscreen: 'Vollbild erzwingen', fullscreenDesc: 'Das Spiel direkt im Vollbildmodus starten', resolution: 'Fensterauflösung', resolutionDesc: 'Standardgröße des Fensters', memory: 'ARBEITSSPEICHER', allocatedRam: 'Zugewiesener RAM', allocatedRamDesc: 'Für Minecraft verfügbarer Arbeitsspeicher', javaArgs: 'JAVA UND STARTARGUMENTE', javaPath: 'Eigener Java-Pfad', javaPathDesc: 'Leer lassen, um das empfohlene mitgelieferte Java zu verwenden', autoDetected: 'Standard (automatisch erkannt)', jvmArgs: 'JVM-Argumente', jvmArgsDesc: 'Zusätzliche Befehlszeilenargumente für Java', directory: 'Instanzordner', directoryDesc: 'Lokale Dateien dieser Instanz', openDirectory: 'Ordner öffnen', saved: 'Änderungen gespeichert', save: 'Einstellungen speichern' },
  mods: { search: 'Installierte Mods suchen…', add: 'Mods hinzufügen', loading: 'Mods werden geladen…', empty: 'In dieser Instanz sind keine Mods installiert.', browse: 'Mods durchsuchen', byAuthor: 'von {author}', remove: 'Mod entfernen' },
  logs: { filter: 'Protokolle filtern…', autoScroll: 'Automatisch scrollen', copied: 'Kopiert', copy: 'Kopieren', uploading: 'Wird hochgeladen…', linkCopied: 'Link kopiert', upload: 'Auf mclo.gs hochladen', empty: 'Noch keine Protokolle. Starte die Instanz, um die Konsole zu sehen.', noMatch: 'Keine Protokolle entsprechen dem Filter.' },
  screenshots: { count: '{count} Screenshot(s)', loading: 'Screenshots werden geladen…', empty: 'In dieser Instanz gibt es noch keine Screenshots.', tip: 'Drücke in Minecraft F2, um einen Screenshot aufzunehmen.' },
  packs: { shaders: 'Shaderpakete', resources: 'Ressourcenpakete', loading: '{type} werden geladen…', empty: 'Keine {type} installiert.', openFolder: 'Ordner {folder} öffnen' },
  day: { mon: 'Mo', tue: 'Di', wed: 'Mi', thu: 'Do', fri: 'Fr', sat: 'Sa', sun: 'So' },
  overview: { subtitle: 'Spielverlauf und Server für {version} {loader}', totalPlaytime: 'Gesamtspielzeit', sessions: 'Sitzungen', average: 'Durchschnittliche Sitzung', activeDays: 'Aktive Tage', serverJoins: 'Serverbeitritte', whenYouPlay: 'Wann du spielst', mostActive: 'Am aktivsten am {day}', peakTime: 'Höchstwert gegen 16 Uhr', day: 'Tag', hour: 'Stunde', dailyPlaytime: 'Tägliche Spielzeit', total: 'Gesamt', samplePeriod: '27 Min. · 22. Juli – 30. Juli' },
  versions: { snapshotDescription: 'Entwicklungsversionen von Mojang. Gut zum Testen neuer Funktionen, aber möglicherweise instabil.', lineDescription: 'Minecraft-{version}-Versionen aus dem offiziellen Manifest. {count} Builds sind verfügbar.', snapshot: 'Snapshot', snapshots: 'Snapshots', experimental: 'Experimentell', release: 'Veröffentlichung', unavailable: 'nicht verfügbar', created: 'Instanz erstellt', ready: '{name} ist spielbereit.', loadingManifest: 'Minecraft-Versionsmanifest wird geladen…', cachedManifest: 'Das gespeicherte Manifest wird angezeigt. Zum Aktualisieren erneut verbinden.', subtitle: 'Wähle eine Version, einen Build und einen Mod-Loader.', fetching: 'Versionen werden von Mojang abgerufen', installedCount: '{count} installiert', buildCount: '{count} Build(s)', version: 'Version', selectVersion: 'Version auswählen', modLoader: 'Mod-Loader', loaderSnapshotUnavailable: '{loader} veröffentlicht keine Builds für Snapshots wie {version}.', loaderNoBuild: '{loader} hat keinen Build für {version}.', loaderMinimum: '{loader} unterstützt Minecraft {version} und neuer.', loaderNoBuildYet: '{loader} hat noch keinen Build für {version}.', alreadyInstalled: 'Bereits als {name} installiert', createInstance: 'Instanz erstellen', openInstance: 'Instanz öffnen', createAndOpen: 'Erstellen und öffnen' },
  browse: { mods: 'Mods', modpacks: 'Modpacks', shaderpacks: 'Shaderpakete', resourcepacks: 'Ressourcenpakete', datapacks: 'Datenpakete', relevance: 'Relevanz', downloads: 'Downloads', followers: 'Follower', newest: 'Neueste', updated: 'Aktualisiert', connectionError: 'Modrinth ist nicht erreichbar. Prüfe deine Verbindung und versuche es erneut.', modpackInstalled: 'Modpack installiert', readyToPlay: '{name} ist spielbereit.', installFailed: 'Installation fehlgeschlagen', couldNotInstall: '{name} konnte nicht installiert werden.', noInstanceSelected: 'Keine Instanz ausgewählt', createBeforeInstall: 'Erstelle vor der Installation eine Instanz.', noDownloads: 'Für dieses Projekt gibt es keine herunterladbaren Versionen.', noExactMatch: 'Keine genaue Übereinstimmung', installingLatest: '{name} hat keinen Build für {target}. Stattdessen wird die neueste Version installiert.', thisInstance: 'diese Instanz', noFile: 'Diese Version enthält keine herunterladbare Datei.', installed: 'Installiert', addedTo: '{name} wurde zu {instance} hinzugefügt.', couldNotRemove: 'Inhalt konnte nicht entfernt werden', removeFailed: 'Dieser Inhalt konnte nicht entfernt werden.', subtitle: 'Inhalte von Modrinth, direkt in eine Instanz installiert.', installingTo: 'Installieren in', noInstances: 'Keine Instanzen', searchType: '{type} suchen', compatibleOnly: 'Nur mit der ausgewählten Instanz kompatible Inhalte anzeigen', compatibleWith: 'Kompatibel mit {version}', categories: 'Kategorien', noCategories: 'Keine Kategorien für diesen Typ.', clearFilters: 'Filter löschen', searching: 'Suche läuft…', resultCount: '{count} Ergebnisse', installingModpack: 'Modpack wird installiert…', nothingFound: 'Nichts gefunden. Lösche Kategorien oder deaktiviere den Kompatibilitätsfilter.', installPack: 'Paket installieren', licence: 'Lizenz', author: 'Autor', unknown: 'Unbekannt', loadingVersions: 'Versionsliste wird geladen…', viewOnModrinth: 'Auf Modrinth ansehen' },
  update: { title: 'Update-Center', close: 'Update-Center schließen', optimizedPatch: 'Optimierter Patch', package: 'Update-Paket', reusingFiles: 'Vorhandene Dateien werden wiederverwendet; nur geänderte Blöcke werden geladen.', installed: 'Installiert', available: 'Verfügbar', differential: 'Differentielle Downloads', verified: 'Vor Installation geprüft', fullPackage: 'Vollständiges Paket ({size})', whatsNew: 'Neuerungen', defaultNotes: 'Leistungsverbesserungen und Launcher-Aktualisierungen.', couldNotComplete: 'Das Update konnte nicht abgeschlossen werden.', currentVersion: 'Aktuelle Version {version}', later: 'Später', download: 'Update herunterladen', restartLater: 'Später neu starten', restartInstall: 'Neu starten und installieren', cancelDownload: 'Download abbrechen', applying: 'Update wird angewendet…', checking: 'Wird geprüft…', check: 'Nach Updates suchen', autoTitle: 'Updates werden automatisch verwaltet', autoText: 'Noctra Client sucht unauffällig und du entscheidest, wann installiert wird.', desktopTitle: 'Desktop-Updates', desktopText: 'Die Update-Suche ist in installierten Builds verfügbar.', checkingTitle: 'Suche nach Updates', checkingText: 'Die neueste stabile Version wird gesucht…', upToDate: 'Alles ist aktuell', newestVersion: 'Noctra Client {version} ist die neueste Version.', readyTitle: 'Noctra Client {version} ist verfügbar', readyText: 'Prüfe die Änderungen und aktualisiere, wenn du bereit bist.', preparingTitle: 'Download wird vorbereitet', preparingText: 'Diese Version wird mit den installierten Dateien verglichen…', downloadingPercent: 'Download {percent} %', changedOnly: 'Nur geänderte Teile werden heruntergeladen.', downloadingText: 'Das Update wird heruntergeladen und geprüft.', installReady: 'Update kann installiert werden', verifiedRestart: 'Noctra Client {version} wurde geprüft. Zum Anwenden neu starten.', restarting: 'Noctra Client wird neu gestartet', applyingMoment: 'Das Update wird gleich angewendet…', interrupted: 'Update unterbrochen', interruptedText: 'Es wurde nichts installiert. Prüfe die Verbindung und versuche es erneut.', estimating: 'Zeit wird berechnet…', secondsRemaining: 'Noch {count} Sek.', minutesRemaining: 'Noch {count} Min.' },
  account: { 'pose.walk': 'Gehen', 'pose.run': 'Laufen', 'pose.idle': 'Stillstehen', 'pose.fly': 'Fliegen', noAccount: 'Noch kein Konto', signedOut: 'Abgemeldet', offlineLong: 'Offline-Konto', microsoftLong: 'Microsoft-Konto', addToPlay: 'Füge ein Konto hinzu, um zu spielen', pause: 'Pausieren', rotate: 'Drehen', yours: 'Deine Konten', count: '{count} Konten', emptyLong: 'Melde dich für Onlinespiele mit Microsoft an oder erstelle ein Offline-Profil.', active: 'Aktiv', removeNamed: '{name} entfernen' },
  storage: { versionManifest: 'Versionsmanifest', versionArtwork: 'Versionsbilder', instanceLibrary: 'Instanzbibliothek', preferences: 'Einstellungen', fullyInstalled: '{count} vollständig installiert', tracked: 'von Noctra Client erfasst', worlds: 'Welten', acrossInstances: 'in allen Instanzen', packs: 'Pakete', packsDesc: 'Ressourcen- und Shaderpakete', recorded: 'vom Launcher erfasst', localCache: 'Lokaler Cache', cacheDesc: 'Manifest, Bilder, Einstellungen', perInstance: 'Pro Instanz', scanning: 'Wird geprüft', rescan: 'Erneut prüfen', empty: 'Noch keine Instanzen; es wird kein Speicherplatz belegt.', notDownloaded: 'Nicht heruntergeladen', modCount: '{count} Mods', worldCount: '{count} Welten', resourcePacks: 'Ressourcenpakete', shaderPacks: 'Shaderpakete', lastPlayed: 'Zuletzt gespielt', never: 'Nie', instanceFolder: 'Instanzordner', cachedData: 'Zwischengespeicherte Daten', clearCaches: 'Download-Caches leeren', cacheEmpty: 'leer' },
  changelog: { error: 'GitHub ist nicht erreichbar. Stelle eine Internetverbindung her, um die Hinweise zu laden.', checking: 'Versionen werden geprüft', upToDate: 'Noctra Client ist aktuell', available: 'Version {version} ist verfügbar', notes: 'Versionshinweise', running: 'Du verwendest {version}', localBuild: 'Lokaler Build', allReleases: 'Alle Versionen', loading: 'Versionshinweise werden geladen…', noReleases: 'Noch keine veröffentlichten Versionen.', installed: 'Installiert', latest: 'Neueste', noNotes: 'Für diese Version gibt es keine Hinweise.', openGitHub: 'Auf GitHub öffnen' },
  settings: { discordPresence: 'Discord-Aktivitätsstatus' }
};

const fr = {
  common: { openFolder: 'Ouvrir le dossier', clear: 'Effacer', previous: 'Précédent', next: 'Suivant' },
  cluster: { overview: 'Vue d’ensemble', logs: 'Journaux', screenshots: 'Captures', mods: 'Mods', shaders: 'Shaders', textures: 'Textures', noneSelected: 'Aucune instance sélectionnée.', kill: 'Arrêter', downloadingPercent: 'Téléchargement {percent} %', downloading: 'Téléchargement…', preparing: 'Préparation…', launch: 'Jouer', vanillaDescription: 'Minecraft {version}, avec ses propres mondes, sauvegardes et paramètres.', loaderDescription: 'Minecraft {version} avec {loader}, ses propres mods, mondes et paramètres.', openGameFolder: 'Ouvrir le dossier du jeu' },
  clusterSettings: { display: 'AFFICHAGE DU JEU', fullscreen: 'Forcer le plein écran', fullscreenDesc: 'Démarrer directement le jeu en plein écran', resolution: 'Résolution de la fenêtre', resolutionDesc: 'Dimensions par défaut de la fenêtre', memory: 'ALLOCATION DE MÉMOIRE', allocatedRam: 'RAM allouée', allocatedRamDesc: 'Mémoire disponible pour Minecraft', javaArgs: 'JAVA ET ARGUMENTS DE LANCEMENT', javaPath: 'Chemin Java personnalisé', javaPathDesc: 'Laisser vide pour utiliser le Java intégré recommandé', autoDetected: 'Par défaut (détection automatique)', jvmArgs: 'Arguments JVM', jvmArgsDesc: 'Arguments supplémentaires transmis à Java', directory: 'Dossier de l’instance', directoryDesc: 'Fichiers locaux de cette instance', openDirectory: 'Ouvrir le dossier', saved: 'Modifications enregistrées', save: 'Enregistrer les paramètres' },
  mods: { search: 'Rechercher dans les mods installés…', add: 'Ajouter des mods', loading: 'Chargement des mods…', empty: 'Aucun mod installé dans cette instance.', browse: 'Parcourir les mods', byAuthor: 'par {author}', remove: 'Supprimer le mod' },
  logs: { filter: 'Filtrer les journaux…', autoScroll: 'Défilement automatique', copied: 'Copié', copy: 'Copier', uploading: 'Envoi…', linkCopied: 'Lien copié', upload: 'Envoyer sur mclo.gs', empty: 'Aucune entrée pour le moment. Lancez cette instance pour afficher la console.', noMatch: 'Aucun journal ne correspond au filtre.' },
  screenshots: { count: '{count} capture(s)', loading: 'Chargement des captures…', empty: 'Aucune capture dans cette instance.', tip: 'Appuyez sur F2 dans Minecraft pour prendre une capture.' },
  packs: { shaders: 'Packs de shaders', resources: 'Packs de ressources', loading: 'Chargement des {type}…', empty: 'Aucun {type} installé.', openFolder: 'Ouvrir le dossier {folder}' },
  day: { mon: 'Lun', tue: 'Mar', wed: 'Mer', thu: 'Jeu', fri: 'Ven', sat: 'Sam', sun: 'Dim' },
  overview: { subtitle: 'Historique de jeu et serveurs pour {version} {loader}', totalPlaytime: 'Temps de jeu total', sessions: 'Sessions', average: 'Session moyenne', activeDays: 'Jours actifs', serverJoins: 'Connexions aux serveurs', whenYouPlay: 'Vos habitudes de jeu', mostActive: 'Plus actif le {day}', peakTime: 'Pic vers 16 h', day: 'Jour', hour: 'Heure', dailyPlaytime: 'Temps de jeu quotidien', total: 'Total', samplePeriod: '27 min · 22 juil. – 30 juil.' },
  versions: { snapshotDescription: 'Versions de développement de Mojang. Pratiques pour tester les nouveautés, mais potentiellement instables.', lineDescription: 'Versions Minecraft {version} du manifeste officiel. {count} builds disponibles.', snapshot: 'Snapshot', snapshots: 'Snapshots', experimental: 'Expérimental', release: 'Version stable', unavailable: 'indisponible', created: 'Instance créée', ready: '{name} est prêt à jouer.', loadingManifest: 'Chargement du manifeste des versions de Minecraft…', cachedManifest: 'Le manifeste en cache est affiché. Reconnectez-vous pour l’actualiser.', subtitle: 'Choisissez une version, un build et un chargeur de mods.', fetching: 'Récupération des versions auprès de Mojang', installedCount: '{count} installée(s)', buildCount: '{count} build(s)', version: 'Version', selectVersion: 'Sélectionner une version', modLoader: 'Chargeur de mods', loaderSnapshotUnavailable: '{loader} ne publie pas de build pour les snapshots tels que {version}.', loaderNoBuild: '{loader} n’a pas de build pour {version}.', loaderMinimum: '{loader} prend en charge Minecraft {version} et les versions ultérieures.', loaderNoBuildYet: '{loader} n’a pas encore de build pour {version}.', alreadyInstalled: 'Déjà installée sous le nom {name}', createInstance: 'Créer l’instance', openInstance: 'Ouvrir l’instance', createAndOpen: 'Créer et ouvrir' },
  browse: { mods: 'Mods', modpacks: 'Modpacks', shaderpacks: 'Packs de shaders', resourcepacks: 'Packs de ressources', datapacks: 'Packs de données', relevance: 'Pertinence', downloads: 'Téléchargements', followers: 'Abonnés', newest: 'Plus récents', updated: 'Mis à jour', connectionError: 'Impossible de joindre Modrinth. Vérifiez la connexion et réessayez.', modpackInstalled: 'Modpack installé', readyToPlay: '{name} est prêt à jouer.', installFailed: 'Échec de l’installation', couldNotInstall: 'Impossible d’installer {name}.', noInstanceSelected: 'Aucune instance sélectionnée', createBeforeInstall: 'Créez une instance avant d’installer du contenu.', noDownloads: 'Ce projet ne propose aucune version téléchargeable.', noExactMatch: 'Aucune correspondance exacte', installingLatest: '{name} n’a pas de build pour {target}. La dernière version sera installée.', thisInstance: 'cette instance', noFile: 'Cette version n’a aucun fichier téléchargeable.', installed: 'Installé', addedTo: '{name} a été ajouté à {instance}.', couldNotRemove: 'Impossible de supprimer le contenu', removeFailed: 'La suppression de ce contenu a échoué.', subtitle: 'Contenu de Modrinth installé directement dans une instance.', installingTo: 'Installer dans', noInstances: 'Aucune instance', searchType: 'Rechercher des {type}', compatibleOnly: 'Afficher uniquement le contenu compatible avec l’instance', compatibleWith: 'Compatible avec {version}', categories: 'Catégories', noCategories: 'Aucune catégorie pour ce type.', clearFilters: 'Effacer les filtres', searching: 'Recherche…', resultCount: '{count} résultats', installingModpack: 'Installation du modpack…', nothingFound: 'Aucun résultat. Effacez les catégories ou désactivez le filtre de compatibilité.', installPack: 'Installer le pack', licence: 'Licence', author: 'Auteur', unknown: 'Inconnu', loadingVersions: 'Chargement des versions…', viewOnModrinth: 'Voir sur Modrinth' },
  update: { title: 'Centre de mise à jour', close: 'Fermer le centre de mise à jour', optimizedPatch: 'Correctif optimisé', package: 'Paquet de mise à jour', reusingFiles: 'Les fichiers présents sont réutilisés ; seuls les blocs modifiés sont téléchargés.', installed: 'Installée', available: 'Disponible', differential: 'Téléchargements différentiels', verified: 'Vérifiée avant installation', fullPackage: 'Paquet complet de {size}', whatsNew: 'Nouveautés', defaultNotes: 'Améliorations des performances et du launcher.', couldNotComplete: 'La mise à jour n’a pas pu aboutir.', currentVersion: 'Version actuelle {version}', later: 'Plus tard', download: 'Télécharger la mise à jour', restartLater: 'Redémarrer plus tard', restartInstall: 'Redémarrer et installer', cancelDownload: 'Annuler le téléchargement', applying: 'Application de la mise à jour…', checking: 'Recherche…', check: 'Rechercher des mises à jour', autoTitle: 'Mises à jour automatiques', autoText: 'Noctra Client vérifie discrètement et vous laisse choisir quand installer.', desktopTitle: 'Mises à jour de bureau', desktopText: 'La recherche de mises à jour est disponible dans l’application installée.', checkingTitle: 'Recherche de mises à jour', checkingText: 'Recherche de la dernière version stable…', upToDate: 'Tout est à jour', newestVersion: 'Noctra Client {version} est la version la plus récente.', readyTitle: 'Noctra Client {version} est disponible', readyText: 'Consultez les changements puis installez quand vous le souhaitez.', preparingTitle: 'Préparation du téléchargement', preparingText: 'Comparaison avec les fichiers déjà installés…', downloadingPercent: 'Téléchargement {percent} %', changedOnly: 'Seules les parties modifiées sont téléchargées.', downloadingText: 'Téléchargement et vérification de la mise à jour.', installReady: 'Mise à jour prête à installer', verifiedRestart: 'Noctra Client {version} est vérifié. Redémarrez pour l’appliquer.', restarting: 'Redémarrage de Noctra Client', applyingMoment: 'La mise à jour va être appliquée…', interrupted: 'Mise à jour interrompue', interruptedText: 'Rien n’a été installé. Vérifiez la connexion et réessayez.', estimating: 'Estimation du temps…', secondsRemaining: '{count} s restantes', minutesRemaining: '{count} min restantes' },
  account: { 'pose.walk': 'Marcher', 'pose.run': 'Courir', 'pose.idle': 'Immobile', 'pose.fly': 'Voler', noAccount: 'Aucun compte', signedOut: 'Déconnecté', offlineLong: 'Compte hors ligne', microsoftLong: 'Compte Microsoft', addToPlay: 'Ajoutez un compte pour jouer', pause: 'Pause', rotate: 'Rotation', yours: 'Vos comptes', count: '{count} comptes', emptyLong: 'Connectez-vous avec Microsoft pour jouer en ligne ou créez un profil hors ligne.', active: 'Actif', removeNamed: 'Supprimer {name}' },
  storage: { versionManifest: 'Manifeste des versions', versionArtwork: 'Illustrations des versions', instanceLibrary: 'Bibliothèque d’instances', preferences: 'Préférences', fullyInstalled: '{count} entièrement installée(s)', tracked: 'suivi par Noctra Client', worlds: 'Mondes', acrossInstances: 'dans toutes les instances', packs: 'Packs', packsDesc: 'packs de ressources et de shaders', recorded: 'enregistré par le launcher', localCache: 'Cache local', cacheDesc: 'manifeste, illustrations, paramètres', perInstance: 'Par instance', scanning: 'Analyse', rescan: 'Réanalyser', empty: 'Aucune instance pour le moment ; aucun espace disque utilisé.', notDownloaded: 'Non téléchargé', modCount: '{count} mods', worldCount: '{count} mondes', resourcePacks: 'Packs de ressources', shaderPacks: 'Packs de shaders', lastPlayed: 'Dernière partie', never: 'Jamais', instanceFolder: 'Dossier de l’instance', cachedData: 'Données en cache', clearCaches: 'Vider les caches de téléchargement', cacheEmpty: 'vide' },
  changelog: { error: 'Impossible de joindre GitHub. Connectez-vous à Internet pour charger les notes.', checking: 'Recherche des versions', upToDate: 'Noctra Client est à jour', available: 'La version {version} est disponible', notes: 'Notes de version', running: 'Vous utilisez {version}', localBuild: 'Build local', allReleases: 'Toutes les versions', loading: 'Chargement des notes…', noReleases: 'Aucune version publiée pour le moment.', installed: 'Installée', latest: 'Dernière', noNotes: 'Aucune note pour cette version.', openGitHub: 'Ouvrir sur GitHub' },
  settings: { discordPresence: 'Activité enrichie Discord' }
};

const ptBR = {
  common: { openFolder: 'Abrir pasta', clear: 'Limpar', previous: 'Anterior', next: 'Próximo' },
  cluster: { overview: 'Visão geral', logs: 'Registros', screenshots: 'Capturas', mods: 'Mods', shaders: 'Shaders', textures: 'Texturas', noneSelected: 'Nenhuma instância selecionada.', kill: 'Parar', downloadingPercent: 'Baixando {percent}%', downloading: 'Baixando…', preparing: 'Preparando…', launch: 'Jogar', vanillaDescription: 'Minecraft {version}, com mundos, saves e configurações separados.', loaderDescription: 'Minecraft {version} com {loader}, mods, mundos e configurações separados.', openGameFolder: 'Abrir pasta do jogo' },
  clusterSettings: { display: 'EXIBIÇÃO DO JOGO', fullscreen: 'Forçar tela cheia', fullscreenDesc: 'Iniciar o jogo diretamente em tela cheia', resolution: 'Resolução da janela', resolutionDesc: 'Dimensões padrão da janela', memory: 'ALOCAÇÃO DE MEMÓRIA', allocatedRam: 'RAM alocada', allocatedRamDesc: 'Memória disponível para o Minecraft', javaArgs: 'JAVA E ARGUMENTOS DE INICIALIZAÇÃO', javaPath: 'Caminho personalizado do Java', javaPathDesc: 'Deixe vazio para usar o Java integrado recomendado', autoDetected: 'Padrão (detectado automaticamente)', jvmArgs: 'Argumentos da JVM', jvmArgsDesc: 'Argumentos adicionais enviados ao Java', directory: 'Pasta da instância', directoryDesc: 'Arquivos locais desta instância', openDirectory: 'Abrir pasta', saved: 'Alterações salvas', save: 'Salvar configurações' },
  mods: { search: 'Buscar mods instalados…', add: 'Adicionar mods', loading: 'Carregando mods…', empty: 'Nenhum mod instalado nesta instância.', browse: 'Explorar mods', byAuthor: 'por {author}', remove: 'Remover mod' },
  logs: { filter: 'Filtrar registros…', autoScroll: 'Rolagem automática', copied: 'Copiado', copy: 'Copiar', uploading: 'Enviando…', linkCopied: 'Link copiado', upload: 'Enviar para mclo.gs', empty: 'Ainda não há registros. Inicie esta instância para ver o console.', noMatch: 'Nenhum registro corresponde ao filtro.' },
  screenshots: { count: '{count} captura(s)', loading: 'Carregando capturas…', empty: 'Ainda não há capturas nesta instância.', tip: 'Pressione F2 no Minecraft para fazer uma captura.' },
  packs: { shaders: 'Pacotes de shaders', resources: 'Pacotes de recursos', loading: 'Carregando {type}…', empty: 'Nenhum {type} instalado.', openFolder: 'Abrir pasta {folder}' },
  day: { mon: 'Seg', tue: 'Ter', wed: 'Qua', thu: 'Qui', fri: 'Sex', sat: 'Sáb', sun: 'Dom' },
  overview: { subtitle: 'Histórico de jogo e servidores de {version} {loader}', totalPlaytime: 'Tempo total', sessions: 'Sessões', average: 'Média por sessão', activeDays: 'Dias ativos', serverJoins: 'Entradas em servidores', whenYouPlay: 'Quando você joga', mostActive: 'Mais ativo na {day}', peakTime: 'Pico por volta das 16h', day: 'Dia', hour: 'Hora', dailyPlaytime: 'Tempo diário', total: 'Total', samplePeriod: '27 min · 22 jul – 30 jul' },
  versions: { snapshotDescription: 'Versões de desenvolvimento da Mojang. Úteis para testar novidades, mas podem ser instáveis.', lineDescription: 'Versões do Minecraft {version} do manifesto oficial. Há {count} builds disponíveis.', snapshot: 'Snapshot', snapshots: 'Snapshots', experimental: 'Experimental', release: 'Versão estável', unavailable: 'indisponível', created: 'Instância criada', ready: '{name} está pronto para jogar.', loadingManifest: 'Carregando o manifesto de versões do Minecraft…', cachedManifest: 'Exibindo o manifesto salvo. Reconecte para atualizar.', subtitle: 'Escolha uma versão, uma build e um mod loader.', fetching: 'Buscando versões da Mojang', installedCount: '{count} instalada(s)', buildCount: '{count} build(s)', version: 'Versão', selectVersion: 'Selecione uma versão', modLoader: 'Mod loader', loaderSnapshotUnavailable: '{loader} não publica builds para snapshots como {version}.', loaderNoBuild: '{loader} não tem uma build para {version}.', loaderMinimum: '{loader} suporta Minecraft {version} e mais recentes.', loaderNoBuildYet: '{loader} ainda não tem uma build para {version}.', alreadyInstalled: 'Já instalada como {name}', createInstance: 'Criar instância', openInstance: 'Abrir instância', createAndOpen: 'Criar e abrir' },
  browse: { mods: 'Mods', modpacks: 'Modpacks', shaderpacks: 'Pacotes de shaders', resourcepacks: 'Pacotes de recursos', datapacks: 'Pacotes de dados', relevance: 'Relevância', downloads: 'Downloads', followers: 'Seguidores', newest: 'Mais recentes', updated: 'Atualizados', connectionError: 'Não foi possível acessar o Modrinth. Verifique a conexão e tente novamente.', modpackInstalled: 'Modpack instalado', readyToPlay: '{name} está pronto para jogar.', installFailed: 'Falha na instalação', couldNotInstall: 'Não foi possível instalar {name}.', noInstanceSelected: 'Nenhuma instância selecionada', createBeforeInstall: 'Crie uma instância antes de instalar conteúdo.', noDownloads: 'Este projeto não tem versões para download.', noExactMatch: 'Sem correspondência exata', installingLatest: '{name} não tem uma build para {target}. A versão mais recente será instalada.', thisInstance: 'esta instância', noFile: 'Essa versão não tem arquivo para download.', installed: 'Instalado', addedTo: '{name} foi adicionado a {instance}.', couldNotRemove: 'Não foi possível remover o conteúdo', removeFailed: 'Falha ao remover esse conteúdo.', subtitle: 'Conteúdo do Modrinth instalado diretamente em uma instância.', installingTo: 'Instalar em', noInstances: 'Sem instâncias', searchType: 'Buscar {type}', compatibleOnly: 'Mostrar apenas conteúdo compatível com a instância', compatibleWith: 'Compatível com {version}', categories: 'Categorias', noCategories: 'Não há categorias para este tipo.', clearFilters: 'Limpar filtros', searching: 'Buscando…', resultCount: '{count} resultados', installingModpack: 'Instalando modpack…', nothingFound: 'Nada encontrado. Limpe as categorias ou desative o filtro de compatibilidade.', installPack: 'Instalar pacote', licence: 'Licença', author: 'Autor', unknown: 'Desconhecido', loadingVersions: 'Carregando lista de versões…', viewOnModrinth: 'Ver no Modrinth' },
  update: { title: 'Central de atualizações', close: 'Fechar central de atualizações', optimizedPatch: 'Patch otimizado', package: 'Pacote de atualização', reusingFiles: 'Os arquivos deste PC serão reutilizados; apenas os blocos alterados serão baixados.', installed: 'Instalada', available: 'Disponível', differential: 'Downloads diferenciais', verified: 'Verificada antes de instalar', fullPackage: 'Pacote completo de {size}', whatsNew: 'Novidades', defaultNotes: 'Melhorias de desempenho e do launcher.', couldNotComplete: 'Não foi possível concluir a atualização.', currentVersion: 'Versão atual {version}', later: 'Mais tarde', download: 'Baixar atualização', restartLater: 'Reiniciar depois', restartInstall: 'Reiniciar e instalar', cancelDownload: 'Cancelar download', applying: 'Aplicando atualização…', checking: 'Verificando…', check: 'Buscar atualizações', autoTitle: 'Atualizações automáticas', autoText: 'O Noctra Client verifica discretamente e você escolhe quando instalar.', desktopTitle: 'Atualizações do aplicativo', desktopText: 'A busca de atualizações está disponível no aplicativo instalado.', checkingTitle: 'Buscando atualizações', checkingText: 'Procurando a versão estável mais recente…', upToDate: 'Tudo atualizado', newestVersion: 'Noctra Client {version} é a versão mais recente.', readyTitle: 'Noctra Client {version} está disponível', readyText: 'Veja as alterações e atualize quando quiser.', preparingTitle: 'Preparando o download', preparingText: 'Comparando esta versão com os arquivos instalados…', downloadingPercent: 'Baixando {percent}%', changedOnly: 'Apenas as partes alteradas serão baixadas.', downloadingText: 'Baixando e verificando a atualização.', installReady: 'Atualização pronta para instalar', verifiedRestart: 'Noctra Client {version} foi verificado. Reinicie para aplicar.', restarting: 'Reiniciando o Noctra Client', applyingMoment: 'A atualização será aplicada em instantes…', interrupted: 'Atualização interrompida', interruptedText: 'Nada foi instalado. Verifique a conexão e tente novamente.', estimating: 'Calculando tempo…', secondsRemaining: '{count}s restantes', minutesRemaining: '{count}min restantes' },
  account: { 'pose.walk': 'Andar', 'pose.run': 'Correr', 'pose.idle': 'Parado', 'pose.fly': 'Voar', noAccount: 'Nenhuma conta', signedOut: 'Sessão encerrada', offlineLong: 'Conta offline', microsoftLong: 'Conta Microsoft', addToPlay: 'Adicione uma conta para jogar', pause: 'Pausar', rotate: 'Girar', yours: 'Suas contas', count: '{count} contas', emptyLong: 'Entre com a Microsoft para jogar online ou crie um perfil offline.', active: 'Ativa', removeNamed: 'Remover {name}' },
  storage: { versionManifest: 'Manifesto de versões', versionArtwork: 'Imagens de versões', instanceLibrary: 'Biblioteca de instâncias', preferences: 'Preferências', fullyInstalled: '{count} totalmente instalada(s)', tracked: 'registrado pelo Noctra Client', worlds: 'Mundos', acrossInstances: 'em todas as instâncias', packs: 'Pacotes', packsDesc: 'pacotes de recursos e shaders', recorded: 'registrado pelo launcher', localCache: 'Cache local', cacheDesc: 'manifesto, imagens e configurações', perInstance: 'Por instância', scanning: 'Analisando', rescan: 'Analisar novamente', empty: 'Ainda não há instâncias; nenhum espaço em disco está sendo usado.', notDownloaded: 'Não baixada', modCount: '{count} mods', worldCount: '{count} mundos', resourcePacks: 'Pacotes de recursos', shaderPacks: 'Pacotes de shaders', lastPlayed: 'Última vez jogada', never: 'Nunca', instanceFolder: 'Pasta da instância', cachedData: 'Dados em cache', clearCaches: 'Limpar caches de download', cacheEmpty: 'vazio' },
  changelog: { error: 'Não foi possível acessar o GitHub. Conecte-se à internet para carregar as notas.', checking: 'Buscando versões', upToDate: 'O Noctra Client está atualizado', available: 'A versão {version} está disponível', notes: 'Notas da versão', running: 'Você está usando {version}', localBuild: 'Build local', allReleases: 'Todas as versões', loading: 'Carregando notas…', noReleases: 'Ainda não há versões publicadas.', installed: 'Instalada', latest: 'Mais recente', noNotes: 'Não há notas para esta versão.', openGitHub: 'Abrir no GitHub' },
  settings: { discordPresence: 'Atividade avançada do Discord' }
};

const tr = {
  common: { openFolder: 'Klasörü aç', clear: 'Temizle', previous: 'Önceki', next: 'Sonraki' },
  cluster: { overview: 'Genel bakış', logs: 'Kayıtlar', screenshots: 'Ekran görüntüleri', mods: 'Modlar', shaders: 'Gölgelendiriciler', textures: 'Dokular', noneSelected: 'Bir kurulum seçilmedi.', kill: 'Durdur', downloadingPercent: 'İndiriliyor {percent}%', downloading: 'İndiriliyor…', preparing: 'Hazırlanıyor…', launch: 'Oyna', vanillaDescription: 'Ayrı dünyaları, kayıtları ve ayarlarıyla Minecraft {version}.', loaderDescription: 'Ayrı modları, dünyaları ve ayarlarıyla Minecraft {version} ve {loader}.', openGameFolder: 'Oyun klasörünü aç' },
  clusterSettings: { display: 'OYUN GÖRÜNTÜSÜ', fullscreen: 'Tam ekranı zorla', fullscreenDesc: 'Oyunu doğrudan tam ekran modunda başlat', resolution: 'Pencere çözünürlüğü', resolutionDesc: 'Varsayılan pencere boyutları', memory: 'BELLEK AYIRMA', allocatedRam: 'Ayrılan RAM', allocatedRamDesc: 'Minecraft için kullanılabilen bellek', javaArgs: 'JAVA VE BAŞLATMA DEĞİŞKENLERİ', javaPath: 'Özel Java yolu', javaPathDesc: 'Önerilen yerleşik Java’yı kullanmak için boş bırak', autoDetected: 'Varsayılan (otomatik algılandı)', jvmArgs: 'JVM değişkenleri', jvmArgsDesc: 'Java’ya iletilen ek komut satırı değişkenleri', directory: 'Kurulum klasörü', directoryDesc: 'Bu kurulumun yerel dosyaları', openDirectory: 'Klasörü aç', saved: 'Değişiklikler kaydedildi', save: 'Ayarları kaydet' },
  mods: { search: 'Yüklü modları ara…', add: 'Mod ekle', loading: 'Modlar yükleniyor…', empty: 'Bu kurulumda mod yüklü değil.', browse: 'Modlara göz at', byAuthor: '{author} tarafından', remove: 'Modu kaldır' },
  logs: { filter: 'Kayıtları filtrele…', autoScroll: 'Otomatik kaydır', copied: 'Kopyalandı', copy: 'Kopyala', uploading: 'Yükleniyor…', linkCopied: 'Bağlantı kopyalandı', upload: 'mclo.gs’ye yükle', empty: 'Henüz kayıt yok. Konsolu görmek için kurulumu başlat.', noMatch: 'Filtrenizle eşleşen kayıt yok.' },
  screenshots: { count: '{count} ekran görüntüsü', loading: 'Ekran görüntüleri yükleniyor…', empty: 'Bu kurulumda henüz ekran görüntüsü yok.', tip: 'Ekran görüntüsü almak için Minecraft’ta F2’ye bas.' },
  packs: { shaders: 'Gölgelendirici paketleri', resources: 'Kaynak paketleri', loading: '{type} yükleniyor…', empty: 'Yüklü {type} yok.', openFolder: '{folder} klasörünü aç' },
  day: { mon: 'Pzt', tue: 'Sal', wed: 'Çar', thu: 'Per', fri: 'Cum', sat: 'Cmt', sun: 'Paz' },
  overview: { subtitle: '{version} {loader} için oyun geçmişi ve sunucular', totalPlaytime: 'Toplam oyun süresi', sessions: 'Oturumlar', average: 'Ortalama oturum', activeDays: 'Etkin günler', serverJoins: 'Sunucu girişleri', whenYouPlay: 'Ne zaman oynuyorsun', mostActive: 'En etkin gün: {day}', peakTime: 'En yoğun saat 16.00 civarı', day: 'Gün', hour: 'Saat', dailyPlaytime: 'Günlük oyun süresi', total: 'Toplam', samplePeriod: '27 dk · 22 Tem – 30 Tem' },
  versions: { snapshotDescription: 'Mojang’ın geliştirme sürümleri. Yenilikleri denemek için uygundur ancak kararsız olabilir.', lineDescription: 'Resmî bildirgedeki Minecraft {version} sürümleri. {count} yapı kullanılabilir.', snapshot: 'Snapshot', snapshots: 'Snapshot’lar', experimental: 'Deneysel', release: 'Kararlı sürüm', unavailable: 'kullanılamıyor', created: 'Kurulum oluşturuldu', ready: '{name} oynamaya hazır.', loadingManifest: 'Minecraft sürüm bildirgesi yükleniyor…', cachedManifest: 'Kaydedilmiş bildirge gösteriliyor. Yenilemek için yeniden bağlan.', subtitle: 'Bir sürüm, yapı ve mod yükleyici seç.', fetching: 'Sürümler Mojang’dan alınıyor', installedCount: '{count} yüklü', buildCount: '{count} yapı', version: 'Sürüm', selectVersion: 'Bir sürüm seç', modLoader: 'Mod yükleyici', loaderSnapshotUnavailable: '{loader}, {version} gibi snapshot’lar için yapı yayımlamıyor.', loaderNoBuild: '{loader} için {version} yapısı yok.', loaderMinimum: '{loader}, Minecraft {version} ve daha yeni sürümleri destekler.', loaderNoBuildYet: '{loader} için henüz {version} yapısı yok.', alreadyInstalled: '{name} adıyla zaten yüklü', createInstance: 'Kurulum oluştur', openInstance: 'Kurulumu aç', createAndOpen: 'Oluştur ve aç' },
  browse: { mods: 'Modlar', modpacks: 'Mod paketleri', shaderpacks: 'Gölgelendirici paketleri', resourcepacks: 'Kaynak paketleri', datapacks: 'Veri paketleri', relevance: 'Alaka', downloads: 'İndirmeler', followers: 'Takipçiler', newest: 'En yeni', updated: 'Güncellenen', connectionError: 'Modrinth’e ulaşılamadı. Bağlantını kontrol edip yeniden dene.', modpackInstalled: 'Mod paketi yüklendi', readyToPlay: '{name} oynamaya hazır.', installFailed: 'Yükleme başarısız', couldNotInstall: '{name} yüklenemedi.', noInstanceSelected: 'Kurulum seçilmedi', createBeforeInstall: 'İçerik yüklemeden önce bir kurulum oluştur.', noDownloads: 'Bu projenin indirilebilir sürümü yok.', noExactMatch: 'Tam eşleşme yok', installingLatest: '{name} için {target} yapısı yok. Bunun yerine en yeni sürüm yüklenecek.', thisInstance: 'bu kurulum', noFile: 'Bu sürümde indirilebilir dosya yok.', installed: 'Yüklendi', addedTo: '{name}, {instance} kurulumuna eklendi.', couldNotRemove: 'İçerik kaldırılamadı', removeFailed: 'Bu içerik kaldırılamadı.', subtitle: 'Modrinth içeriğini doğrudan bir kuruluma yükle.', installingTo: 'Yüklenecek yer', noInstances: 'Kurulum yok', searchType: '{type} ara', compatibleOnly: 'Yalnızca seçili kurulumla uyumlu içeriği göster', compatibleWith: '{version} ile uyumlu', categories: 'Kategoriler', noCategories: 'Bu tür için kategori yok.', clearFilters: 'Filtreleri temizle', searching: 'Aranıyor…', resultCount: '{count} sonuç', installingModpack: 'Mod paketi yükleniyor…', nothingFound: 'Sonuç bulunamadı. Kategorileri temizle veya uyumluluk filtresini kapat.', installPack: 'Paketi yükle', licence: 'Lisans', author: 'Yazar', unknown: 'Bilinmiyor', loadingVersions: 'Sürüm listesi yükleniyor…', viewOnModrinth: 'Modrinth’te görüntüle' },
  update: { title: 'Güncelleme merkezi', close: 'Güncelleme merkezini kapat', optimizedPatch: 'İyileştirilmiş yama', package: 'Güncelleme paketi', reusingFiles: 'Bu bilgisayardaki dosyalar yeniden kullanılıyor; yalnızca değişen bloklar indiriliyor.', installed: 'Yüklü', available: 'Kullanılabilir', differential: 'Fark indirmeleri', verified: 'Yüklemeden önce doğrulandı', fullPackage: '{size} tam paket', whatsNew: 'Yenilikler', defaultNotes: 'Performans iyileştirmeleri ve başlatıcı güncellemeleri.', couldNotComplete: 'Güncelleme tamamlanamadı.', currentVersion: 'Geçerli sürüm {version}', later: 'Daha sonra', download: 'Güncellemeyi indir', restartLater: 'Daha sonra yeniden başlat', restartInstall: 'Yeniden başlat ve yükle', cancelDownload: 'İndirmeyi iptal et', applying: 'Güncelleme uygulanıyor…', checking: 'Denetleniyor…', check: 'Güncellemeleri denetle', autoTitle: 'Güncellemeler otomatik yönetilir', autoText: 'Noctra Client sessizce denetler; ne zaman yükleneceğine sen karar verirsin.', desktopTitle: 'Masaüstü güncellemeleri', desktopText: 'Güncelleme denetimi kurulu uygulamada kullanılabilir.', checkingTitle: 'Güncellemeler denetleniyor', checkingText: 'En yeni kararlı sürüm aranıyor…', upToDate: 'Her şey güncel', newestVersion: 'Noctra Client {version} en yeni sürüm.', readyTitle: 'Noctra Client {version} hazır', readyText: 'Değişiklikleri incele ve hazır olduğunda güncelle.', preparingTitle: 'İndirme hazırlanıyor', preparingText: 'Bu sürüm yüklü dosyalarla karşılaştırılıyor…', downloadingPercent: 'İndiriliyor {percent}%', changedOnly: 'Yalnızca değişen bölümler indiriliyor.', downloadingText: 'Güncelleme indiriliyor ve doğrulanıyor.', installReady: 'Güncelleme yüklemeye hazır', verifiedRestart: 'Noctra Client {version} doğrulandı. Uygulamak için yeniden başlat.', restarting: 'Noctra Client yeniden başlatılıyor', applyingMoment: 'Güncelleme birazdan uygulanacak…', interrupted: 'Güncelleme kesildi', interruptedText: 'Hiçbir şey yüklenmedi. Bağlantını kontrol edip yeniden dene.', estimating: 'Süre hesaplanıyor…', secondsRemaining: '{count} sn kaldı', minutesRemaining: '{count} dk kaldı' },
  account: { 'pose.walk': 'Yürü', 'pose.run': 'Koş', 'pose.idle': 'Bekle', 'pose.fly': 'Uç', noAccount: 'Henüz hesap yok', signedOut: 'Oturum kapalı', offlineLong: 'Çevrimdışı hesap', microsoftLong: 'Microsoft hesabı', addToPlay: 'Oynamak için bir hesap ekle', pause: 'Duraklat', rotate: 'Döndür', yours: 'Hesapların', count: '{count} hesap', emptyLong: 'Çevrimiçi oynamak için Microsoft ile oturum aç veya çevrimdışı profil oluştur.', active: 'Etkin', removeNamed: '{name} hesabını kaldır' },
  storage: { versionManifest: 'Sürüm bildirgesi', versionArtwork: 'Sürüm görselleri', instanceLibrary: 'Kurulum kitaplığı', preferences: 'Tercihler', fullyInstalled: '{count} tamamen yüklü', tracked: 'Noctra Client tarafından izleniyor', worlds: 'Dünyalar', acrossInstances: 'tüm kurulumlarda', packs: 'Paketler', packsDesc: 'kaynak ve gölgelendirici paketleri', recorded: 'başlatıcı tarafından kaydedildi', localCache: 'Yerel önbellek', cacheDesc: 'bildirge, görseller, ayarlar', perInstance: 'Kurulum başına', scanning: 'Taranıyor', rescan: 'Yeniden tara', empty: 'Henüz kurulum yok; disk alanı kullanılmıyor.', notDownloaded: 'İndirilmedi', modCount: '{count} mod', worldCount: '{count} dünya', resourcePacks: 'Kaynak paketleri', shaderPacks: 'Gölgelendirici paketleri', lastPlayed: 'Son oynama', never: 'Hiç', instanceFolder: 'Kurulum klasörü', cachedData: 'Önbelleğe alınan veriler', clearCaches: 'İndirme önbelleklerini temizle', cacheEmpty: 'boş' },
  changelog: { error: 'GitHub’a ulaşılamadı. Sürüm notlarını yüklemek için internete bağlan.', checking: 'Sürümler denetleniyor', upToDate: 'Noctra Client güncel', available: '{version} sürümü kullanılabilir', notes: 'Sürüm notları', running: '{version} sürümünü kullanıyorsun', localBuild: 'Yerel yapı', allReleases: 'Tüm sürümler', loading: 'Sürüm notları yükleniyor…', noReleases: 'Henüz yayımlanmış sürüm yok.', installed: 'Yüklü', latest: 'En yeni', noNotes: 'Bu sürüm için not yazılmamış.', openGitHub: 'GitHub’da aç' },
  settings: { discordPresence: 'Discord Zengin Etkinliği' }
};

export const FEATURE_CATALOGS = {
  en: flattenSections(en),
  es: flattenSections(es),
  de: flattenSections(de),
  fr: flattenSections(fr),
  'pt-BR': flattenSections(ptBR),
  tr: flattenSections(tr)
};
